pipeline {
    agent {
        node {
        label 'master'
        customWorkspace env.JOB_NAME/env.BRANCH
        }
    }

    stages {

        stage('Test') {
            steps {
                echo 'Hi from prod ...'
                echo env.BRANCH
            }
        }


        stage('Deploy') {
            steps {
                echo 'Deployment'
                    sh ''' 
                    ssh eva@evablis "  
                    pwd && ls s
                    "
                    '''
                    } 
                }

    }
}
