pipeline {
    agent {
        node {
        label 'dev-server'
        customWorkspace env.BRANCH
        }
    }
    
    stages {

        stage('Test') {
            steps {
                echo 'Hi from main ...'
                sh 'pwd'
                echo env.BRANCH
            }
        }

    }
}
