pipeline {

    agent {
        node {
        label 'dev-server'
        customWorkspace  "${JOB_BASE_NAME}/${BRANCH}"
        }
    }
    stages {

        stage('Test') {
            steps {
                echo 'Hi from main ...'
                sh 'pwd'
                echo env.BRANCH
        }

    }
        stage('Deploy') {
            steps {
                echo 'Deployment'
                    sh ''' 
                    echo $JOB_NAME
                    ssh eva@evablis "  
                    pwd && ls
                    "
                    '''
                    } 
                }
  }
}